# HTCondor submit description file
# Everything with a leading # is a comment

universe                = vanilla
initialdir              = /nethome/ajdsouza/vllm_server
executable              = start_vllm.sh
output	                = /scratch/ajdsouza/vllm_server/run.sh.$(ClusterId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).out
error                   = /scratch/ajdsouza/vllm_server/run.sh.$(ClusterId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).err
log                     = /scratch/ajdsouza/vllm_server/run.sh.$(ClusterId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).log
request_CPUs            = 16
request_memory          = 150G
request_GPUs            = 1
requirements            = (GPUs_GlobalMemoryMb >= 50000) && (TARGET.UidDomain == "coli.uni-saarland.de")

getenv                  = True
+WantGPUHomeMounted     = true

queue 1

# go to docker hub and get your docker image or else build from scratch:
# https://hub.docker.com/r/huggingface/transformers-pytorch-gpu

 
